### PR TITLE
chore(prisma) Upgrade to Prisma v.3

### PR DESCRIPTION
**Pull request by nina-py**
## Goal

Upgrade Prisma to the latest version. 

## Implementation Decisions

There are some breaking changes that we need to take into account - constraints now have a different naming convention and the options are to keep the old constraint names or update the db schema to use the new naming conventions: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3/named-constraints/#option-2-i-want-to-use-prismas-default-constraint-and-index-names. 

Additionally, custom names for constraints are no longer allowed to be the same as the field name this constraint is on (the convention followed in this repository). I chose the path of removing all custom names and run 

```bash
docker compose exec app npx prisma migrate dev --name update-constraint-names-to-v3-defaults
```

to have them all renamed to the new standard.

We also need to review if we need to change anything with regards to referential actions: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3/referential-actions. As far as I know, we need to clean up collection story authors if a collection story is deleted. 

## Todos

- [x] Fix tests.
- [x] Update branch.
- [x] Update seed script invocation to the Prisma 3 way of doing things.
- [x] Make a decision on referential actions - updated `CollectionStoryAuthor` to add `onDelete: Cascade`.

### CODE REVIEW

**Comment by nina-py** [comment]
@jpetto, would appreciate your input with the referential actions action item above!

**Comment by nina-py** [comment]
Deployment to dev failed at the installation step. Hmm...

**Comment by nina-py** [comment]
Updated branch and did another push to `dev` and this time the deployment succeeded thanks to the work @bassrock did behind the scenes.

**Review by jpetto — APPROVED** [review]
i think this is good to go - but question: do we have a way to backup dbs in AWS before doing potentially risky operations?

**Comment by nina-py** [comment]
That's probably a @izo3 question! Let me ping him before I pull the plug. Given it's near the end of the day for him, I'll ask and let this PR sit unmerged till tomorrow.

**Comment by nina-py** [comment]
@jpetto, here's Hristo's reply:

> in this case, if the db is small, we could take a snapshot, then you can uprade drop/recreate the indexes. If things go south, we would restore from snapshot. Keep in mind, if we need to restore, there will be some data loss, time needed to get the rds online from snapshot. We could have a restored RDS from snapshot on standby, before the operation, then if things don’t work out, we point to the restored RDS.

Does that sound like something you could coordinate with Hristo tomorrow morning?

**Pull request merged**
